# Copyright 2020 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  api:
    image: ord-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PG_DSN: "postgresql+asyncpg://ord@db:5432/ord"
      PG_TEST_DSN: "postgresql+psycopg://ord@db:5432/test"
      APP_ENV: "localhost"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - ord_network

  db:
    image: bitnamilegacy/postgresql:17
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRESQL_DATABASE: ord
      POSTGRESQL_USERNAME: ord
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
    volumes:
      - db:/bitnami/postgresql
    ports:
      - "5400:5432"
    networks:
      - ord_network
    healthcheck:
      test: pg_isready -U ord
      interval: 5s
      retries: 6
      start_period: 1s

  migrate:
    image: ord-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_DSN: "postgresql+psycopg://ord@db:5432/ord"
      PG_ALEMBIC_DSN: "postgresql+psycopg://ord@db:5432/ord"
    volumes:
      - .:/app
    entrypoint: >
      sh -c "alembic upgrade head"
    networks:
      - ord_network
    restart: "no"

networks:
  ord_network:
    name: ord_network

volumes:
  db: