[tool.poetry]
name = "ord-app"
version = "0.1.0"
description = "App for the Open Reaction Database"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
fastapi = "0.115.6"
gunicorn = "==23.0.0"
jinja2 = "==3.1.4"
numpy = "==2.1.3"
ord-schema = "==0.3.91"
pandas = "==2.2.3"
protobuf = "==4.22.3"
psycopg = "3.2.3"
rdkit = "2024.9.5"
uvicorn = "0.34.0"
setuptools = "^75.6.0"
python-multipart = "0.0.19"
alembic = "1.14.0"
sqlalchemy = "2.0.36"
pydantic-settings = "2.6.1"
greenlet = "3.1.1"
sqlalchemy-utils = "0.41.2"
passlib = "1.7.4"
pydantic = {version = "2.10.3", extras = ["email"]}
orjson = "^3.10.12"
fastapi-pagination = "0.12.32"
loguru = "^0.7.3"
ruff = "^0.9.1"
pytest = "^8.3.4"
freezegun = "^1.5.1"
asyncpg = "^0.30.0"

[tool.poetry.group.dev.dependencies]
black = "24.10.0"
coverage = "7.6.8"
httpx = "0.28.0"
pylint = "3.3.2"
pytest-cov = "6.0.0"
pytype = "2024.10.11"
tenacity = "9.0.0"
testing-postgresql = "1.3.0"
pytest = "8.3.4"
pytest-asyncio = "0.24.0"

[tool.black]
line-length = 120

[tool.isort]
skip_glob = ["**/*_pb2.py*"]
line_length = 120
profile = "black"
known_third_party = ["ord_schema"]

[tool.pytype]
inputs = ["ord_app"]
exclude = ["**/*_test.py", "**/test_*.py", "build/", "dist/"]
keep_going = true
disable = ["module-attr", "pyi-error"]
jobs = 0

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"