# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""add unique constraint for reaction on name and dataset_id fields and rename reaction name field to pb_reaction_id and makes it required

Revision ID: 0cf068176338
Revises: 29065bc738da
Create Date: 2025-02-05 13:09:01.623013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf068176338'
down_revision: Union[str, None] = '29065bc738da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('pb_reaction_id', sa.String(), nullable=False))
    op.create_unique_constraint('uq_pb_reaction_id_dataset_id', 'reaction', ['pb_reaction_id', 'dataset_id'])
    op.drop_column('reaction', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_pb_reaction_id_dataset_id', 'reaction', type_='unique')
    op.drop_column('reaction', 'pb_reaction_id')
    # ### end Alembic commands ###
