# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""change user fields

Revision ID: 200ebb1f465d
Revises: 1987c9f3670e
Create Date: 2024-12-16 23:59:21.088814

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "200ebb1f465d"
down_revision: Union[str, None] = "1987c9f3670e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("identities", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column("user", "first_name")
    op.drop_column("user", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("user", sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("user", "identities")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
