# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""update user

Revision ID: 3f8361592497
Revises: ada3e6c3df9c
Create Date: 2024-12-25 15:37:39.961105

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f8361592497"
down_revision: Union[str, None] = "ada3e6c3df9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("external_id", sa.String(), nullable=True))
    op.drop_index("ix_user_auth0_id", table_name="user")
    op.create_index(op.f("ix_user_external_id"), "user", ["external_id"], unique=False)
    op.drop_column("user", "auth0_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("auth0_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_user_external_id"), table_name="user")
    op.create_index("ix_user_auth0_id", "user", ["auth0_id"], unique=False)
    op.drop_column("user", "external_id")
    # ### end Alembic commands ###
