# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""remove group from reaction

Revision ID: 54d2a4b0995b
Revises: 2f6458a34fd3
Create Date: 2025-01-13 12:54:11.078130

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54d2a4b0995b"
down_revision: Union[str, None] = "2f6458a34fd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reaction_group_id", table_name="reaction")
    op.drop_constraint("reaction_group_id_fkey", "reaction", type_="foreignkey")
    op.drop_column("reaction", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reaction", sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key("reaction_group_id_fkey", "reaction", "group", ["group_id"], ["id"], ondelete="CASCADE")
    op.create_index("ix_reaction_group_id", "reaction", ["group_id"], unique=False)
    # ### end Alembic commands ###
