"""add unique constraint for reaction on name and dataset_id fields and rename reaction name field to pb_reaction_id and makes it required

Revision ID: 660a82626f00
Revises: 29065bc738da
Create Date: 2025-02-04 13:37:53.125061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660a82626f00'
down_revision: Union[str, None] = '29065bc738da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('pb_reaction_id', sa.String(), nullable=False))
    op.create_unique_constraint('uq_pb_reaction_id_dataset_id', 'reaction', ['pb_reaction_id', 'dataset_id'])
    op.drop_column('reaction', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_pb_reaction_id_dataset_id', 'reaction', type_='unique')
    op.drop_column('reaction', 'pb_reaction_id')
    # ### end Alembic commands ###
