# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""change user model

Revision ID: ac84697e2259
Revises: 200ebb1f465d
Create Date: 2024-12-17 22:51:16.111817

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

from ord_app.service_api.models import AuthProviders

# revision identifiers, used by Alembic.
revision: str = "ac84697e2259"
down_revision: Union[str, None] = "200ebb1f465d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("user", sa.Column("external_id", sa.String(), nullable=True))
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=255), nullable=True)

    op.add_column(
        "user",
        sa.Column("auth_provider", sqlalchemy_utils.types.choice.ChoiceType(choices=AuthProviders), nullable=True),
    )
    op.execute("UPDATE \"user\" SET auth_provider = 'platform' WHERE auth_provider IS NULL")
    op.alter_column("user", "auth_provider", nullable=False)

    op.drop_column("user", "identities")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("identities", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("user", "auth_provider")
    op.drop_column("user", "external_id")
    op.drop_column("user", "avatar_url")
    # ### end Alembic commands ###
