# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""add field is_primary group

Revision ID: b0c2bda3f16c
Revises: de9e8b9fd5ec
Create Date: 2025-02-12 23:53:58.935359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c2bda3f16c'
down_revision: Union[str, None] = 'de9e8b9fd5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_group_association', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.execute("UPDATE dataset_group_association SET is_primary = false")
    op.alter_column('dataset_group_association', 'is_primary', existing_type=sa.Boolean(), nullable=False, default=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_group_association', 'is_primary')
    # ### end Alembic commands ###
