# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""change source column to binpb

Revision ID: d2c94da4fe95
Revises: cfa07096bc5a
Create Date: 2024-12-11 17:18:43.071143

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2c94da4fe95"
down_revision: Union[str, None] = "cfa07096bc5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reaction", sa.Column("binpb", sa.LargeBinary(), nullable=True))
    op.drop_column("reaction", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reaction", sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False)
    )
    op.drop_column("reaction", "binpb")
    # ### end Alembic commands ###
