# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""add ondelete cascade for DatasetGroupAssociationModel

Revision ID: e4f613ed3029
Revises: 54d2a4b0995b
Create Date: 2025-01-15 23:12:15.855225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f613ed3029'
down_revision: Union[str, None] = '54d2a4b0995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_group_association_dataset_id_fkey', 'dataset_group_association', type_='foreignkey')
    op.drop_constraint('dataset_group_association_group_id_fkey', 'dataset_group_association', type_='foreignkey')
    op.create_foreign_key(None, 'dataset_group_association', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dataset_group_association', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset_group_association', type_='foreignkey')
    op.drop_constraint(None, 'dataset_group_association', type_='foreignkey')
    op.create_foreign_key('dataset_group_association_group_id_fkey', 'dataset_group_association', 'group', ['group_id'], ['id'])
    op.create_foreign_key('dataset_group_association_dataset_id_fkey', 'dataset_group_association', 'dataset', ['dataset_id'], ['id'])
    # ### end Alembic commands ###
