"""add ondelete cascade for DatasetGroupAssociationModel

Revision ID: e4f613ed3029
Revises: 54d2a4b0995b
Create Date: 2025-01-15 23:12:15.855225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f613ed3029'
down_revision: Union[str, None] = '54d2a4b0995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_group_association_dataset_id_fkey', 'dataset_group_association', type_='foreignkey')
    op.drop_constraint('dataset_group_association_group_id_fkey', 'dataset_group_association', type_='foreignkey')
    op.create_foreign_key(None, 'dataset_group_association', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dataset_group_association', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset_group_association', type_='foreignkey')
    op.drop_constraint(None, 'dataset_group_association', type_='foreignkey')
    op.create_foreign_key('dataset_group_association_group_id_fkey', 'dataset_group_association', 'group', ['group_id'], ['id'])
    op.create_foreign_key('dataset_group_association_dataset_id_fkey', 'dataset_group_association', 'dataset', ['dataset_id'], ['id'])
    # ### end Alembic commands ###
