# Copyright 2024 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""change index types

Revision ID: fdca65b9b209
Revises: 85f3c3d0b2e8
Create Date: 2025-03-12 13:16:17.639632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdca65b9b209'
down_revision: Union[str, None] = '85f3c3d0b2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reaction_pb_reaction_id', 'reaction', ['pb_reaction_id'], unique=False, postgresql_using='hash')
    op.alter_column('template', 'user_id', nullable=False, new_column_name='owner_id')
    op.drop_index('ix_template_user_id', table_name='template')
    op.create_index('ix_template_owner_id', 'template', ['owner_id'], unique=False, postgresql_using='hash')
    op.drop_constraint('template_user_id_fkey', 'template', type_='foreignkey')
    op.create_foreign_key(None, 'template', 'user', ['owner_id'], ['id'])
    op.drop_index('ix_user_auth0_id', table_name='user')
    op.drop_index('ix_user_orcid_id', table_name='user')
    op.create_unique_constraint(None, 'user', ['auth0_id'])
    op.create_unique_constraint(None, 'user', ['orcid_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_orcid_id', 'user', ['orcid_id'], unique=True)
    op.create_index('ix_user_auth0_id', 'user', ['auth0_id'], unique=True)
    op.add_column('template', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.create_foreign_key('template_user_id_fkey', 'template', 'user', ['user_id'], ['id'])
    op.drop_index('ix_template_owner_id', table_name='template', postgresql_using='hash')
    op.create_index('ix_template_user_id', 'template', ['user_id'], unique=False)
    op.drop_column('template', 'owner_id')
    op.drop_index('ix_reaction_pb_reaction_id', table_name='reaction', postgresql_using='hash')
    # ### end Alembic commands ###
