# Copyright 2020 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:

  test_python:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-14"]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres
        with:
          username: ord
          password: password
          database: test
          port: 5432
          postgres-version: "17"
          ssl: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install dependencies
        run: |
          poetry add greenlet
          poetry install --with dev --no-interaction --no-ansi

      - name: Run alembic migrations
        run: poetry run alembic upgrade head
        env:
          PG_DSN: "postgresql+psycopg://ord:password@localhost:5432/test"
          PG_ALEMBIC_DSN: "postgresql+psycopg://ord:password@localhost:5432/test"
          PG_TEST_DSN: "postgresql+psycopg://ord:password@localhost:5432/test"

      - name: Run tests
        run: poetry run pytest -vv --cov=ord_app --durations=10
        env:
          PG_DSN: "postgresql+asyncpg://ord:password@localhost:5432/test"
          PG_ALEMBIC_DSN: "postgresql+psycopg://ord:password@localhost:5432/test"
          PG_TEST_DSN: "postgresql+psycopg://ord:password@localhost:5432/test"
